- hosts: all
  become: yes
  tasks:
    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install Neofetch
    - name: Install Neofetch
      apt:
        name: neofetch
        state: present

    # Check if user "narokuu" exists
    - name: Check if user "narokuu" exists
      command: id -u narokuu
      register: narokuu_user_check
      ignore_errors: yes

    # Set target user based on presence of "narokuu"
    - name: Set target user variable
      set_fact:
        target_user: "{{ 'narokuu' if narokuu_user_check.rc == 0 else 'root' }}"
        target_home: "{{ '/home/narokuu' if narokuu_user_check.rc == 0 else '/root' }}"

    # Ensure Neofetch runs on startup for the target user
    - name: Ensure Neofetch runs on startup
      lineinfile:
        path: "{{ target_home }}/.bashrc"
        line: "neofetch"
        state: present
        create: yes

    # Ensure Neofetch config directory exists for the target user
    - name: Ensure Neofetch config directory exists
      file:
        path: "{{ target_home }}/.config/neofetch"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    # Create or update Neofetch config file for the target user
    - name: Create or update Neofetch config file
      copy:
        dest: "{{ target_home }}/.config/neofetch/config.conf"
        content: |
          # Neofetch configuration file
          # See https://github.com/dylanaraps/neofetch/wiki/Customizing-Info for customization options

          # Default display options
          print_info() {
            info title
            info underline
            info "OS" distro
            info "Kernel" kernel
            info "Uptime" uptime
            info "Packages" packages
            info "Shell" shell
            info "Resolution" resolution
            info "DE" de
            info "WM" wm
            info "Theme" theme
            info "Icons" icons
            info "Terminal" term
            info "CPU" cpu
            info "Memory" memory
            info "Disk" disk
            info "IP Address" ip
          }
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'