- hosts: all
  become: yes
  become_user: root
  tasks:
    # Update package cache and install Neofetch
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Neofetch
      apt:
        name: neofetch
        state: present

    # Check if Neofetch is already in .bashrc
    - name: Check if Neofetch is in .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "neofetch"
        state: present
        create: yes

    # Reload .bashrc to apply changes
    - name: Reload .bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash